<a href="https://colab.research.google.com/github/Ashu202023/Ashu202023/blob/main/Using_decision_tree_classification_on_apple_quality_dataset__from_keggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Classification

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


## Importing the dataset

In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving kaggle.json to kaggle.json


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!kaggle datasets list -s Apple


ref                                                      title                                       size  lastUpdated          downloadCount  voteCount  usabilityRating  
-------------------------------------------------------  -----------------------------------------  -----  -------------------  -------------  ---------  ---------------  
nelgiriyewithana/apple-quality                           Apple Quality                              170KB  2024-01-11 14:31:07           2428         61  1.0              
varpit94/apple-stock-data-updated-till-22jun2021         APPLE Stock Data                           205KB  2022-03-25 16:13:47           4318         65  1.0              
gauthamp10/apple-appstore-apps                           Apple AppStore Apps                        117MB  2021-10-14 07:28:30           3360         48  0.85294116       
tarunpaparaju/apple-aapl-historical-stock-data           Apple (AAPL) Historical Stock Data          49KB  2020-02-29 08:58:43          1054

In [ ]:
!kaggle datasets download nelgiriyewithana/apple-quality

  0% 0.00/170k [00:00<?, ?B/s]
100% 170k/170k [00:00<00:00, 84.3MB/s]


In [ ]:
!unzip -q /content/apple-quality.zip -d /content/

replace /content/apple_quality.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [ ]:
data=pd.read_csv("apple_quality.csv")


In [ ]:
data.isna().sum()

A_id           1
Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [ ]:
data=data.dropna()

In [ ]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
y

array(['good', 'good', 'bad', ..., 'good', 'good', nan], dtype=object)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
data.head(10)

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0   0.0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1   1.0 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2   2.0 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3   3.0 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4   4.0  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
5   5.0 -3.425400 -1.409082  -1.913511    -0.555775  -3.853071  1.914616   
6   6.0  1.331606  1.635956   0.875974    -1.677798   3.106344 -1.847417   
7   7.0 -1.995462 -0.428958   1.530644    -0.742972   0.158834  0.974438   
8   8.0 -3.867632 -3.734514   0.986429    -1.207655   2.292873  4.080921   
9   9.0 -0.727983 -0.442820  -4.092223     0.597513   0.393714  1.620857   

        Acidity Quality  
0  -0.491590483    good  
1  -0.722809367    good  
2   2.621636473     bad  
3   0.790723217    good  
4   0.501984036    good  
5  -2.981523169     bad  
6   2.414170509    good  
7  -1.470125066    good  
8  -4.871904758     bad  
9   2.185607723     bad

In [ ]:
x_train

array([[678.0, -0.075144754, 1.684715494, ..., 0.014954763, 1.84105985,
        '-2.570587079'],
       [2427.0, 1.689363891, 1.291571154, ..., 0.657549319, -0.556177335,
        '0.156466706'],
       [3574.0, -3.093009038, -0.671068245, ..., -1.589697141,
        2.579041333, '-2.291247659'],
       ...,
       [1653.0, -0.119942585, 0.432874321, ..., -0.882093839,
        1.952705471, '0.592650517'],
       [2607.0, -3.95593209, 3.516142427, ..., -0.495453259, -0.68849119,
        '-2.046503511'],
       [2732.0, 1.129720039, 0.121569397, ..., 2.020415326, -2.182337417,
        '1.264944552']], dtype=object)

In [ ]:
y_train

array(['bad', 'good', 'bad', ..., 'good', 'good', 'good'], dtype=object)

In [ ]:
x_test

array([[2230.0, -0.882113631, -0.63021827, ..., -2.922814821,
        0.701124631, '-1.187544333'],
       [668.0, 1.46580644, -2.775201154, ..., -1.440469112, 3.638384588,
        '0.352908697'],
       [3616.0, -0.028301416, 0.673264832, ..., 0.925253121, 0.288044808,
        '-1.992564683'],
       ...,
       [3668.0, 1.067835473, -2.3637292, ..., -1.351699815, 3.430219056,
        '-1.134481826'],
       [576.0, 0.294586351, -0.353755252, ..., 0.671989996, 1.291838185,
        '0.920605642'],
       [1504.0, -5.489663623, -0.879753802, ..., 3.60891774, 0.701062208,
        '3.068997143']], dtype=object)

In [ ]:
y_test

array(['bad', 'good', 'good', 'bad', 'bad', 'good', 'good', 'bad', 'good',
       'bad', 'bad', 'good', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad',
       'good', 'good', 'bad', 'bad', 'bad', 'good', 'good', 'bad', 'bad',
       'bad', 'bad', 'bad', 'good', 'good', 'good', 'good', 'good', 'bad',
       'bad', 'bad', 'bad', 'good', 'good', 'bad', 'bad', 'bad', 'bad',
       'bad', 'good', 'bad', 'good', 'good', 'good', 'bad', 'good', 'bad',
       'good', 'good', 'bad', 'bad', 'good', 'good', 'bad', 'bad', 'bad',
       'good', 'bad', 'bad', 'bad', 'good', 'good', 'bad', 'good', 'bad',
       'bad', 'good', 'bad', 'good', 'good', 'bad', 'bad', 'bad', 'bad',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'bad',
       'bad', 'good', 'good', 'good', 'bad', 'bad', 'good', 'bad', 'bad',
       'bad', 'bad', 'good', 'good', 'good', 'good', 'bad', 'bad', 'bad',
       'bad', 'bad', 'good', 'good', 'bad', 'good', 'good', 'bad', 'bad',
       'good', 'bad', 'bad', 'bad', 'bad', 'ba

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

[]


## Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(random_state=0)
model.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [ ]:
x_test

array([[ 0.19513425, -0.19825433,  0.24181296, ..., -1.79069248,
         0.09622643, -0.59441468],
       [-1.16627763,  1.02370872, -1.11311462, ..., -1.01897167,
         1.66158299,  0.14292497],
       [ 1.4031476 ,  0.24610789,  1.06518793, ...,  0.2126419 ,
        -0.12391657, -0.97973861],
       ...,
       [ 1.44846989,  0.81658676, -0.85319893, ..., -0.97275767,
         1.55064515, -0.56901625],
       [-1.24646322,  0.41415319,  0.41644716, ...,  0.08079113,
         0.41103593,  0.41465378],
       [-0.43763465, -2.59623029,  0.08418813, ...,  1.60977877,
         0.09619316,  1.4429839 ]])

## Making the Confusion Matrix

In [ ]:
# y_pred=model.predict(x_test)
# x_test[:, 7] = x_test[:, 7].astype(float)
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
accuracy_score(y_test,y_pred)


[[384 122]
 [103 391]]


0.775